plugins {
	id "checkstyle"
	id "java-gradle-plugin"
	id "io.spring.javaformat" version "$javaFormatVersion"
}

repositories {
	mavenCentral()
	gradlePluginPortal()
	maven {
		name = "Spring Snapshots"
		url = "https://repo.spring.io/snapshot"
	}
}

dependencies {
	checkstyle("com.puppycrawl.tools:checkstyle:${checkstyle.toolVersion}")
	checkstyle("io.spring.javaformat:spring-javaformat-checkstyle:${javaFormatVersion}")

	implementation("io.spring.javaformat:spring-javaformat-gradle-plugin:$javaFormatVersion")
	implementation("io.spring.gradle.nullability:nullability-plugin:0.0.1-SNAPSHOT")
}

gradlePlugin {
	plugins {
		conventionsPlugin {
			id = "org.springframework.ws.conventions"
			implementationClass = "org.springframework.ws.gradle.conventions.ConventionsPlugin"
		}
	}
}
